apiVersion: {{ include "poddisruptionbudgetversion" .}}
kind: PodDisruptionBudget
metadata:
  name: blackbox-exporter
  namespace: kube-system
  labels:
    gardener.cloud/role: monitoring
    component: blackbox-exporter
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: blackbox-exporter
