# TODO (acumino): drop this chart in release v1.75
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
