{{- if not .Values.config.runtimeClientConnection.kubeconfig }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required ".Values.serviceAccountName is required" .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.invalidateServiceAccountToken }}
{{- if semverCompare ">= 1.20-0" .Capabilities.KubeVersion.GitVersion }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end }}
