apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: gardener.kube-system.vpn-shoot
spec:
  privileged: true
  volumes:
  - secret
  - emptyDir
  allowedCapabilities:
  - NET_ADMIN
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
