apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: gardener.cloud:psp:privileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
