---
apiVersion: controllermanager.config.gardener.cloud/v1alpha1
kind: ControllerManagerConfiguration
gardenClientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
controllers:
  plant:
    syncPeriod: 10s
    concurrentSyncs: 5
  seed:
    concurrentSyncs: 5
    syncPeriod: 30s
  # monitorPeriod: 40s
  # shootMonitorPeriod: 300s
  shootMaintenance:
    concurrentSyncs: 5
  # enableShootControlPlaneRestarter: true
  shootHibernation:
    concurrentSyncs: 5
  shootQuota:
    concurrentSyncs: 5
    syncPeriod: 60m
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: configmaps
# `discovery` allows specifying options for the cached discovery client.
# discovery:
#   discoveryCacheDir: /tmp/cache-dir
#   httpCacheDir: /tmp/http-cache-dir
#   ttl: 10s
logLevel: info
kubernetesLogLevel: 0
server:
  http:
    bindAddress: 0.0.0.0
    port: 2718
  https:
    bindAddress: 0.0.0.0
    port: 2719
    tls:
      serverCertPath: dev/tls/gardener-controller-manager.crt
      serverKeyPath: dev/tls/gardener-controller-manager.key
