# CredentialsBinding bind a Secret or WorkloadIdentity from the same or
# another namespace together with Quotas from the same or other namespaces.
---
apiVersion: authentication.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: my-provider-account
  namespace: garden-dev
provider:
  type: <some-provider-name> # {aws,azure,gcp,...}
credentials:
  secretRef:
    name: my-provider-account
  # namespace: namespace-other-than-'garden-dev' // optional
  workloadIdentityRef:
    name: my-provider-account
  # namespace: namespace-other-than-'garden-dev' // optional
quotas: []
# - name: quota-1
# # namespace: namespace-other-than-'garden-dev' // optional
