apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: gardener.cloud:psp:{{ template "nginx-ingress.fullname" . }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:privileged
subjects:
- kind: ServiceAccount
  name: {{ template "nginx-ingress.fullname" . }}
  namespace: kube-system
