apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:addons-nginx-ingress
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore

