apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-local
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: local-skaffold/gardener-extension-provider-local:latest