apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-addon-manager-admission-controls
  namespace: {{.Release.Namespace}}
data:
{{- range $key, $val := .Values.AdmissionControlsContent }}
  {{ $key | replace "/" "_" }}: |
{{ $val | indent 4 }}
{{- end}}