apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sshd_deployment.yaml

configMapGenerator:
- name: gardener-apiserver-sshd
  namespace: relay
  files:
  - files/sshd_config
  - files/entrypoint.sh

