apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  upstream: gcr

resources:
- ../base

patches:
- target:
    group: apps
    kind: Deployment
    name: registry
  patch: |
    - op: replace
      path: /metadata/name
      value: registry-gcr
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
      - name: REGISTRY_PROXY_REMOTEURL
        value: https://gcr.io
      - name: REGISTRY_HTTP_ADDR
        value: :5003
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 5003
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /etc/gardener/local-registry/gcr
