description: GardenletDeployment specifies certain gardenlet deployment parameters,
  such as the number of replicas, the image, etc.
properties:
  additionalVolumeMounts:
    description: AdditionalVolumeMounts is the list of additional pod volumes to mount
      into the gardenlet container's filesystem.
    items:
      $ref: blueprint://schema/io.k8s.api.core.v1.VolumeMount.yaml
      default: {}
    type: array
  additionalVolumes:
    description: AdditionalVolumes is the list of additional volumes that should be
      mounted by gardenlet containers.
    items:
      $ref: blueprint://schema/io.k8s.api.core.v1.Volume.yaml
      default: {}
    type: array
  env:
    description: Env is the list of environment variables to set in the gardenlet
      container.
    items:
      $ref: blueprint://schema/io.k8s.api.core.v1.EnvVar.yaml
      default: {}
    type: array
  image:
    $ref: blueprint://schema/com.github.gardener.gardener.pkg.apis.seedmanagement.v1alpha1.Image.yaml
    description: Image is the gardenlet container image.
  podAnnotations:
    additionalProperties:
      default: ""
      type: string
    description: PodAnnotations are the annotations on gardenlet pods.
    type: object
  podLabels:
    additionalProperties:
      default: ""
      type: string
    description: PodLabels are the labels on gardenlet pods.
    type: object
  replicaCount:
    description: ReplicaCount is the number of gardenlet replicas. Defaults to 1.
    format: int32
    type: integer
  resources:
    $ref: blueprint://schema/io.k8s.api.core.v1.ResourceRequirements.yaml
    description: Resources are the compute resources required by the gardenlet container.
  revisionHistoryLimit:
    description: RevisionHistoryLimit is the number of old gardenlet ReplicaSets to
      retain to allow rollback. Defaults to 10.
    format: int32
    type: integer
  serviceAccountName:
    description: ServiceAccountName is the name of the ServiceAccount to use to run
      gardenlet pods.
    type: string
  vpa:
    description: VPA specifies whether to enable VPA for gardenlet. Defaults to true.
    type: boolean
type: object
