# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shoot-info
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
