global:
  kubernetesVersion: 1.20.1
  podNetwork: 100.96.0.0/11
  vpaEnabled: false
apiserver-proxy:
  enabled: false
  images:
    apiserver-proxy: image-repository
    apiserver-proxy-sidecar: image-repository
  advertiseIPAddress: 1.1.1.1
  # webhook:
    # caBundle: LS0tLS1C
  proxySeedServer:
    host: dummy.127.0.0.1.nip.io
    port: 8443
monitoring:
  enabled: true
  node-exporter:
    images:
      node-exporter: image-repository:image-tag
network-policies:
  enabled: true
podsecuritypolicies:
  enabled: true
  allowPrivilegedContainers: false
shoot-info:
  enabled: true
vertical-pod-autoscaler:
  enabled: false
