global:
  vpaEnabled: false
  pspDisabled: false
  hasWorkers: true
monitoring:
  enabled: true
  node-exporter:
    images:
      node-exporter: image-repository:image-tag
podsecuritypolicies:
  enabled: true
  allowPrivilegedContainers: false
