run:
  concurrency: 4
  deadline: 10m

  skip-dirs:
  - pkg/client/core
  - pkg/client/extensions
  - pkg/client/seedmanagement
  - pkg/client/settings

  skip-files:
  - ".*\\.pb\\.go$"
  - "zz_generated\\..*\\.go$"
  - "openapi_generated\\.go$"

linters:
  disable:
  - unused
  enable:
  - golint

issues:
  exclude-use-default: false
  exclude:
  # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  # golint:
  - (don't use underscores in Go names;|don't use an underscore in package name)
  - ((var|const|struct field) `.*` should be `.*`|func .* should be .*)
  - a blank import should be only in a main or test package, or have a comment justifying it
  - should not use dot imports
  - package comment should be of the form
  - (type|func) name will be used as .* by other packages, and that stutters;
  - exported func .* returns unexported type .*, which can be annoying to use
  - "`if` block ends with a `return` statement, so drop this `else` and outdent its block"
  - if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
