apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: garden
manifests:
  rawYaml:
    - example/operator/20-garden.yaml
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command:
              - bash
              - -ec
              - hack/usage/wait-for.sh garden local VirtualGardenAPIServerAvailable RuntimeComponentsHealthy VirtualComponentsHealthy
        - host:
            command:
              - bash
              - -ec
              - kubectl -n garden get secret gardener -o jsonpath={.data.kubeconfig} | base64 -d > dev/virtual-garden-kubeconfig
