---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: etcd
deploy:
  kubectl:
    manifests:
    - example/00-namespace-garden.yaml
  kustomize:
    paths:
    - example/gardener-local/etcd

---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: controlplane
requires:
- configs:
  - etcd
build:
  local:
    concurrency: 0
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/apiserver
    ko:
      main: ./cmd/gardener-apiserver
  - image: eu.gcr.io/gardener-project/gardener/controller-manager
    ko:
      main: ./cmd/gardener-controller-manager
  - image: eu.gcr.io/gardener-project/gardener/scheduler
    ko:
      main: ./cmd/gardener-scheduler
  - image: eu.gcr.io/gardener-project/gardener/admission-controller
    ko:
      main: ./cmd/gardener-admission-controller
deploy:
  helm:
    releases:
    - name: gardener-controlplane
      chartPath: charts/gardener/controlplane
      namespace: garden
      createNamespace: true
      wait: true
      artifactOverrides:
        global:
          apiserver:
            image: eu.gcr.io/gardener-project/gardener/apiserver
          controller:
            image: eu.gcr.io/gardener-project/gardener/controller-manager
          scheduler:
            image: eu.gcr.io/gardener-project/gardener/scheduler
          admission:
            image: eu.gcr.io/gardener-project/gardener/admission-controller
      imageStrategy:
        helm: {}
      valuesFiles:
      - example/gardener-local/controlplane/values.yaml

---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: provider-local
build:
  local:
    concurrency: 0
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/provider-local
    ko:
      main: ./cmd/gardener-extension-provider-local
deploy:
  helm:
    releases:
    - name: gardener-extension-provider-local-registration
      chartPath: charts/gardener/provider-local/registration
      namespace: garden
      artifactOverrides:
        values:
          image: eu.gcr.io/gardener-project/gardener/extensions/provider-local
      imageStrategy:
        helm: {}
profiles:
- name: kind2
  patches:
    # The deploy stage must be skipped because provider-local can only be registered in the garden cluster.
    # The build stage is still necessary so that the image can be loaded into the kind cluster later on.
  - op: remove
    path: /deploy

---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: local-env
deploy:
  kubectl:
    manifests:
    - example/gardener-local/gardenlet/secret-bootstrap-token.yaml
  kustomize:
    paths:
    - example/provider-local/garden/skaffold
    - example/provider-local/seed-kind/skaffold

---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kind2-env
profiles:
- name: kind2
  deploy:
    kubectl:
      manifests:
      - example/00-namespace-garden.yaml
    kustomize:
      paths:
      - example/provider-local/seed-kind2/skaffold

---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: gardenlet
build:
  local:
    concurrency: 0
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/gardenlet
    ko:
      main: ./cmd/gardenlet
      fromImage: eu.gcr.io/gardener-project/alpine-openvpn:3.16.2
  - image: eu.gcr.io/gardener-project/gardener/resource-manager
    ko:
      main: ./cmd/gardener-resource-manager
  - image: eu.gcr.io/gardener-project/gardener/seed-admission-controller
    ko:
      main: ./cmd/gardener-seed-admission-controller
deploy:
  helm:
    hooks:
      after:
      - host:
          command:
          - bash
          - -ec
          - |
            echo "Wait until seed is ready"
            for i in `seq 1 30`;
            do
              if kubectl get seed local 2> /dev/null; then
                break
              fi
              echo "Wait until seed gets created by gardenlet"
              sleep 2
            done
            kubectl wait --for=condition=gardenletready --for=condition=extensionsready --for=condition=bootstrapped seed local --timeout=5m
    releases:
    - name: gardener-gardenlet
      chartPath: charts/gardener/gardenlet
      namespace: garden
      createNamespace: true
      wait: true
      artifactOverrides:
        global:
          gardenlet:
            image: eu.gcr.io/gardener-project/gardener/gardenlet
          # dummy artifact overrides to make skaffold load images into cluster
          resource-manager:
            image: eu.gcr.io/gardener-project/gardener/resource-manager
          seed-admission-controller:
            image: eu.gcr.io/gardener-project/gardener/seed-admission-controller
      setValueTemplates:
        global:
          gardenlet:
            # on a local cluster, skaffold uses a local immutable tag for artifacts,
            # overwrite our image vector to use the image that was just built
            # see https://skaffold.dev/docs/pipeline-stages/taggers/#how-tagging-works
            imageVectorOverwrite: |
              images:
              - name: gardenlet
                repository: localhost:5001/eu_gcr_io_gardener-project_gardener_gardenlet
                tag: "{{.IMAGE_TAG6}}"
              - name: gardener-resource-manager
                repository: localhost:5001/eu_gcr_io_gardener-project_gardener_resource-manager
                tag: "{{.IMAGE_TAG7}}"
              - name: gardener-seed-admission-controller
                repository: localhost:5001/eu_gcr_io_gardener-project_gardener_seed-admission-controller
                tag: "{{.IMAGE_TAG8}}"
      imageStrategy:
        helm: {}
      valuesFiles:
      - example/gardener-local/gardenlet/values.yaml
profiles:
- name: kind2
  patches:
  - op: replace
    path: /deploy/helm/hooks/after/0/host/command
    value:
    - bash
    - -ec
    - |
      echo "Wait until seed is ready"
      for i in `seq 1 30`;
      do
        if kubectl --kubeconfig=$GARDENER_LOCAL_KUBECONFIG get seed local2 2> /dev/null; then
          break
        fi
        echo "Wait until seed gets created by gardenlet"
        sleep 2
      done
      kubectl --kubeconfig=$GARDENER_LOCAL_KUBECONFIG wait --for=condition=gardenletready --for=condition=extensionsready --for=condition=bootstrapped seed local2 --timeout=5m
  - op: add
    path: /deploy/helm/releases/0/valuesFiles/-
    value: example/gardener-local/gardenlet/values-kind2.yaml
    # for the kind2 profile only 4 images are built: provider-local, gardenlet, resource-manager and gardener-seed-admission-controller
    # so the imageVectorOverwrite must be patched to specify the correct tags
  - op: replace
    path: /deploy/helm/releases/0/setValueTemplates
    value:
      global:
        gardenlet:
          imageVectorOverwrite: |
            images:
            - name: gardener-resource-manager
              repository: localhost:5001/eu_gcr_io_gardener-project_gardener_resource-manager
              tag: "{{.IMAGE_TAG3}}"
            - name: gardener-seed-admission-controller
              repository: localhost:5001/eu_gcr_io_gardener-project_gardener_seed-admission-controller
              tag: "{{.IMAGE_TAG4}}"
