# TODO(dimityrmirchev): remove this secret after v1.101 is released
# it is required so that the workload identity can be created successfully
# in local environment with gardener v1.100
apiVersion: v1
kind: Secret
metadata:
  name: local
  namespace: garden-local
type: Opaque
---
apiVersion: security.gardener.cloud/v1alpha1
kind: WorkloadIdentity
metadata:
  name: local
  namespace: garden-local
spec:
  audiences:
  - "provider-local"
  targetSystem:
    type: local
---
apiVersion: security.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: local
  namespace: garden-local
credentialsRef:
  apiVersion: security.gardener.cloud/v1alpha1
  kind: WorkloadIdentity
  name: local
  namespace: garden-local
provider:
  type: local
