apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudprofile.yaml
- controller-registration.yaml
- project.yaml
- secret-backup.yaml
- secretbinding.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-cilium/v1.22.0/example/controller-registration.yaml

patchesStrategicMerge:
- patch-controller-registrations.yaml
- patch-controller-deployment.yaml
