apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: networking-cilium
providerConfig:
  values:
    image:
      # TODO(scheererj): Drop this file and use v1.23.0 image in `kustomization.yaml` once it's released.
      # Currently dev image is used to include https://github.com/gardener/gardener-extension-networking-cilium/pull/166
      tag: v1.23.0-dev-80ebba768e74b108024f67e75c9bc4d923fbe52e