---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: garden
spec:
  namespace: garden
---
apiVersion: v1
kind: Namespace
metadata:
  name: garden-local
  labels:
    gardener.cloud/role: project
    project.gardener.cloud/name: local
---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: local
spec:
  namespace: garden-local
