---
apiVersion: {{ include "apiserviceversion" . }}
kind: APIService
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  version: v1beta1
  versionPriority: 100
  caBundle: {{ required ".Values.tls.caBundle is required" .Values.tls.caBundle }}
