# The static tokens of the secrets generated out of this `ServiceAccount` will be invalidated because it sets
# .automountServiceAccountToken=false.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example1
  namespace: default
automountServiceAccountToken: false

# The static tokens of the secrets generated out of this `ServiceAccount` will NOT be invalidated because it sets
# .labels["token-invalidator.resources.gardener.cloud/skip"]=="true" which overrules
# .automountServiceAccountToken=false.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example2
  namespace: default
  labels:
    token-invalidator.resources.gardener.cloud/skip: "true"
automountServiceAccountToken: false

# The static tokens of the secrets generated out of this `ServiceAccount` will NOT be invalidated because it sets
# .automountServiceAccountToken=true.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example3
  namespace: default
automountServiceAccountToken: true
