apiVersion: v1
kind: Namespace
metadata:
  name: haconfig
  labels:
    high-availability-config.resources.gardener.cloud/consider: "true"
  annotations:
    high-availability-config.resources.gardener.cloud/zones: a,b,c
    high-availability-config.resources.gardener.cloud/failure-tolerance-type: zone | # ""|node|zone
