apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
data:

  # Configuration file for the mesh networks to be used by the Split Horizon EDS.
  meshNetworks: |-
    networks: {}

  mesh: |-
    accessLogFile: "/dev/stdout"

    defaultConfig:
      discoveryAddress: istiod.{{ .Release.Namespace }}.svc:15012

    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true

    rootNamespace: {{ .Release.Namespace }}
    trustDomain: cluster.local
