apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  upstream: docker-ipv6

resources:
- ../base

patches:
- target:
    group: apps
    kind: Deployment
    name: registry
  patch: |
    - op: replace
      path: /metadata/name
      value: registry-docker-ipv6
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
      - name: REGISTRY_PROXY_REMOTEURL
        value: https://registry.ipv6.docker.com
      - name: REGISTRY_HTTP_ADDR
        value: :5008
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 5008
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /etc/gardener/local-registry/docker-ipv6
