apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Disables all Egress traffic from
      this namespace.
  name: deny-all-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-shoot-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          app: kubernetes
          gardener.cloud/role: controlplane
          role: apiserver
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-shoot-vpn-seed-server
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - ports:
    - port: 1194
      protocol: TCP
    to:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          app: vpn-seed-server
          gardener.cloud/role: controlplane
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-reversed-vpn-auth-server
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - ports:
    - port: 9001
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          role: garden
    - podSelector:
        matchLabels:
          app: reversed-vpn-auth-server
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-dns
  namespace:  {{ .Release.Namespace }}

spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    - port: 8053
      protocol: UDP
    - port: 8053
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - kube-dns
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - node-local-dns
    - ipBlock:
        cidr: {{ .Values.dnsServerAddress }}/32
    - ipBlock:
        cidr: {{ .Values.nodeLocalIPVSAddress }}/32
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
  - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-istiod
  namespace:  {{ .Release.Namespace }}
spec:
  egress:
  - ports:
    - port: 15012
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
    - podSelector:
        matchLabels:
          app: istiod
  podSelector:
    matchLabels:
      app: istio-ingressgateway
  policyTypes:
  - Egress
