{{- if not .Values.global.config.sourceClientConnection.kubeconfig }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-resource-manager-target
  labels:
    app: gardener
    role: resource-manager
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener-resource-manager-target
  labels:
    app: gardener
    role: resource-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener-resource-manager-target
subjects:
- kind: ServiceAccount
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
{{- end }}
