apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-resource-manager
  labels:
    app: gardener
    role: resource-manager
webhooks:
{{- if .Values.global.config.webhooks.crdDeletionProtection.enabled }}
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    {{- if .Values.global.config.server.webhooks.ca }}
    caBundle: {{ b64enc .Values.global.config.server.webhooks.ca }}
    {{- end }}
    service:
      name: gardener-resource-manager
      namespace: {{ .Release.Namespace }}
      path: /webhooks/validate-crd-deletion
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: crd-deletion-protection.resources.gardener.cloud
  objectSelector:
    matchLabels:
      gardener.cloud/deletion-protected: "true"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    apiVersions:
    - v1beta1
    - v1
    operations:
    - DELETE
    resources:
    - customresourcedefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    {{- if .Values.global.config.server.webhooks.ca }}
    caBundle: {{ b64enc .Values.global.config.server.webhooks.ca }}
    {{- end }}
    service:
      name: gardener-resource-manager
      namespace: {{ .Release.Namespace }}
      path: /webhooks/validate-crd-deletion
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: cr-deletion-protection.resources.gardener.cloud
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - druid.gardener.cloud
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - etcds
  - apiGroups:
    - extensions.gardener.cloud
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - backupbuckets
    - backupentries
    - bastions
    - containerruntimes
    - controlplanes
    - dnsrecords
    - extensions
    - infrastructures
    - networks
    - operatingsystemconfigs
    - workers
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
{{- end }}
