apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  podSelector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
