# TODO(rfranzke): Delete this Helm chart in a future version.
{{- if .Values.vpaEnabled }}
{{- range $i, $pool := .Values.workerPools }}
---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "kube-proxy.name" $pool }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
{{- end }}
