# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-proxy
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
