# TODO(rfranzke): Delete this Helm chart in a future version.
{{- range $i, $pool := .Values.workerPools }}
---
apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  name: {{ include "kube-proxy.name" $pool }}
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
