apiVersion: garden.sapcloud.io/v1beta1
kind: BackupInfrastructure
metadata:
  name: {{ .Values.backupInfrastructure.name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.backupInfrastructure.annotations }}
  annotations:
{{ toYaml .Values.backupInfrastructure.annotations | indent 4 }}
{{- end }}
  ownerReferences:
  - apiVersion: garden.sapcloud.io/v1beta1
    blockOwnerDeletion: false
    controller: true
    kind: Shoot
    name: {{ .Values.shoot.name }}
    uid: {{ .Values.shoot.uid }}
spec:
  seed: {{ .Values.seed.name }}
  shootUID: {{ .Values.shoot.uid }}
