apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.4/components.yaml

images:
- name: k8s.gcr.io/metrics-server/metrics-server
  newName: registry.k8s.io/metrics-server/metrics-server

patches:
- path: metrics-deployment_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: metrics-server
