apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ssh_deployment.yaml

configMapGenerator:
- name: gardener-apiserver-ssh
  namespace: relay
  files:
  - files/ssh_config
  - files/entrypoint.sh
- name: gardener-apiserver-ssh-keys
  namespace: relay
  files:
  - client-keys/host
  - client-keys/known_hosts
  - client-keys/provider-extensions_id_rsa
  - client-keys/provider-extensions_id_rsa.pub
