apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - port: 443
    targetPort: registry
    protocol: TCP
