apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ssh_deployment.yaml

configMapGenerator:
- name: gardener-apiserver-ssh
  files:
  - files/ssh_config
  - files/entrypoint.sh
