apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: addons-nginx-ingress-nginx-ingress-k8s-backend
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
