{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    addonmanager.kubernetes.io/mode: Reconcile
  name: {{ template "nginx-ingress.fullname" . }}
  namespace: kube-system
{{- end -}}
