apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: garden

secretGenerator:
- name: etcd-tls
  files:
  - tls/ca.crt
  - tls/server.crt
  - tls/server.key

resources:
- networkpolicy.yaml
- service.yaml
- statefulset.yaml
