apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app: registry     
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
  annotations:
    # TLS cert by managed gardener
    cert.gardener.cloud/commonname: $HOST
    cert.gardener.cloud/dnsnames: $HOST
    cert.gardener.cloud/purpose: managed
    cert.gardener.cloud/secretname: registry-tls
    # DNS managed by gardener
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/ttl: "600"
    dns.gardener.cloud/dnsnames: $HOST
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - port: 443
    targetPort: registry
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  serviceName: registry-svc
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      automountServiceAccountToken: false
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /htpasswd/auth
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        ports:
        - name: registry
          containerPort: 5000
        volumeMounts:
        - name: registry-volume
          mountPath: /var/lib/registry
        - name: tls
          mountPath: /certs
        - name: htpasswd
          mountPath: /htpasswd
      volumes:
      - name: tls
        secret:
          secretName: registry-tls
      - name: htpasswd
        secret:
          secretName: registry-htpasswd
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: registry
      name: registry-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
