apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: managedseed
  namespace: garden
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
    shoot.gardener.cloud/cloud-config-execution-max-delay-seconds: "0"
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local
  region: local
  networking:
    type: calico
    # TODO(scheererj): Drop this emtpy provider config after v1.71 has been released (otherwise, e2e upgrade tests break)
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
  provider:
    type: local
    workers:
    - name: local
      machine:
        type: local
      cri:
        name: containerd
      minimum: 1
      maximum: 1
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    version: 1.24.8
    kubelet:
      serializeImagePulls: false
      registryPullQPS: 10
      registryBurst: 20
