{{- define "gardener.secret-default-domain" -}}
{{- range $key, $domain := .Values.global.defaultDomains }}
---
apiVersion: v1
kind: Secret
metadata:
  name: default-domain-{{ ( required ".defaultDomains[].domain is required" (replace "." "-" $domain.domain) ) }}
  namespace: garden
  labels:
    app: gardener
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    garden.sapcloud.io/role: default-domain
    gardener.cloud/role: default-domain
  annotations:
    # keep deprecated dns.garden.sapcloud.io labels for backwards compatibility
    dns.garden.sapcloud.io/provider: {{ ( required ".defaultDomains[].provider is required" $domain.provider ) }}
    dns.garden.sapcloud.io/domain: {{ ( required ".defaultDomains[].domain is required" $domain.domain ) }}
    dns.gardener.cloud/provider: {{ ( required ".defaultDomains[].provider is required" $domain.provider ) }}
    dns.gardener.cloud/domain: {{ ( required ".defaultDomains[].domain is required" $domain.domain ) }}
type: Opaque
data:
{{ toYaml $domain.credentials | indent 2 }}
{{- end }}
{{- end -}}
