---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: {{ .Name }}
    uid: {{ .NamespaceUID | quote }}
    controller: false
    blockOwnerDeletion: false
spec:
  workloadSelector:
    labels:
{{- range $k, $v := .IstioIngressGateway.Labels }}
      {{ $k }}: {{ $v }}
{{- end }}
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: ANY
      listener:
        portNumber: 8443
        name: 0.0.0.0_8443
    patch:
      operation: ADD
      value:
        filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: "outbound|{{ .Port }}||{{ .Host }}"
            cluster: "outbound|{{ .Port }}||{{ .Host }}"
        filter_chain_match:
          destination_port: {{ .Port }}
          prefix_ranges:
          - address_prefix: {{ .APIServerClusterIP }}
            prefix_len: 32
{{- if .ReversedVPN.Enabled }}
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_8132
        portNumber: 8132
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: "envoy.filters.network.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          route_config:
            virtual_hosts:
            - name: {{ .Name }}
              domains:
              - {{ .APIServerInternalDNSName }}:8132
              routes:
              - match:
                  connect_matcher: {}
                route:
                  cluster: outbound|1194||{{ .VPNSeedServerServiceName }}.{{ .Name }}.svc.cluster.local
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config: {}
{{- end }}
