# TODO(ary92): Delete this Helm chart in a future version.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
