# TODO(ary92): Delete this Helm chart in a future version.
---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: node-problem-detector
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
