apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# TODO(plkokanov): upgrade calico version after https://github.com/projectcalico/calico/issues/8541 is fixed.
# We currently use 'v3.27.0' because this issue affects versions 'v3.27.1' and 'v3.27.2'.
- https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/calico.yaml

images:
- name: docker.io/calico/cni
  newName: quay.io/calico/cni
- name: docker.io/calico/node
  newName: quay.io/calico/node
- name: docker.io/calico/kube-controllers
  newName: quay.io/calico/kube-controllers
