apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.24.0
  extraPortMappings:
  # istio-ingressgateway
  # TODO (plkokanov): when using skaffold to deploy, 127.0.0.2 is not used as listenAddress (unlike the local deployment)
  # because secondary IPs cannot be easily added to inside the `prow` containers. Additionally, there is no way currently to
  # swap the dns record of the shoot's `kube-apiserver` once it is migrated to this seed.
  - containerPort: 30443
    hostPort: 9443
  extraMounts:
  - hostPath: dev/local-backupbuckets
    containerPath: /etc/gardener/local-backupbuckets
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authorization-mode: RBAC,Node
networking:
  disableDefaultCNI: true # disable kindnet since we install calico for network policy support
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16