apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.24.7
  extraPortMappings:
  # istio-ingressgateway
  - containerPort: 30443
    hostPort: 443
    listenAddress: 127.0.0.2
  extraMounts:
  - hostPath: dev/local-backupbuckets
    containerPath: /etc/gardener/local-backupbuckets
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authorization-mode: RBAC,Node
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    maxPods: 500
    serializeImagePulls: false
    registryPullQPS: 10
    registryBurst: 20
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["http://gardener-local-control-plane:5002"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
    endpoint = ["http://gardener-local-control-plane:5003"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."eu.gcr.io"]
    endpoint = ["http://gardener-local-control-plane:5004"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
    endpoint = ["http://gardener-local-control-plane:5005"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
    endpoint = ["http://gardener-local-control-plane:5006"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
    endpoint = ["http://gardener-local-control-plane:5007"]
networking:
  disableDefaultCNI: true # disable kindnet since we install calico for network policy support
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16
