groups:
- name: prometheus.rules
  rules:
  - alert: PrometheusCantScrape
    # Alert only if there are jobs but no samples scraped.
    expr: scrape_samples_scraped == 0 and on(job) up == 1
    for: 1h
    labels:
      service: prometheus
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Prometheus failed to scrape metrics. Instance {{ $labels.instance }}, job {{ $labels.job }}.
      summary: No metrics are scraped from any target.
  - alert: PrometheusConfigurationFailure
    expr: prometheus_config_last_reload_successful == 0
    for: 1h
    labels:
      service: prometheus
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Latest Prometheus configuration is broken and Prometheus is using the previous one.
      summary: Prometheus is misconfigured

  - alert: PrometheusBlackboxSslCertificateWillExpireSoon
    expr:  probe_ssl_earliest_cert_expiry{job=~".*ingress.*"} - time() <= 86400*3
    for: 5m
    labels:
      service: prometheus
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Blackbox SSL certificate will expire in 3 days
      summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})"
