kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-local
  name: aws
spec:
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: eu-west-1b
            workers: 10.250.0.0/19
            public: 10.250.32.0/20
            internal: 10.250.48.0/20
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker-nsgya
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: m5.xlarge
          image:
            name: gardenlinux
            version: 576.11.0
          architecture: amd64
        zones:
          - eu-west-1b
        cri:
          name: containerd
        volume:
          type: gp3
          size: 50Gi
  networking:
    nodes: 10.250.0.0/16
    type: calico
  cloudProfileName: aws
  secretBindingName: aws
  region: eu-west-1
  purpose: evaluation
  kubernetes:
    version: 1.24.3
    enableStaticTokenKubeconfig: true
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    timeWindow:
      begin: 020000+0200
      end: 030000+0200
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    schedules:
      - start: 00 17 * * 1,2,3,4,5
        location: Europe/Berlin
