kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-local
  name: azure
spec:
  provider:
    type: azure
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.250.0.0/16
        workers: 10.250.0.0/16
      zoned: true
    controlPlaneConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker-eh9y3
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: Standard_B4ms
          image:
            name: gardenlinux
            version: 576.11.0
          architecture: amd64
        zones:
          - '1'
        cri:
          name: containerd
        volume:
          type: StandardSSD_LRS
          size: 50Gi
  networking:
    nodes: 10.250.0.0/16
    type: calico
  cloudProfileName: az
  region: westeurope
  secretBindingName: azure
  kubernetes:
    version: 1.24.2
    enableStaticTokenKubeconfig: true
  purpose: evaluation
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    timeWindow:
      begin: 030000+0200
      end: 040000+0200
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    schedules:
      - start: 00 17 * * 1,2,3,4,5
        location: Europe/Berlin
