kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-local
  name: gcp-shoot
spec:
  provider:
    type: gcp
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-d
    workers:
      - name: worker-l5wew
        minimum: 1
        maximum: 2
        maxSurge: 1
        machine:
          type: n1-standard-2
          image:
            name: gardenlinux
            version: 576.10.0
        zones:
          - europe-west1-d
        cri:
          name: containerd
        volume:
          type: pd-balanced
          size: 50Gi
  networking:
    nodes: 10.250.0.0/16
    type: calico
  cloudProfileName: gcp
  region: europe-west1
  secretBindingName: gcp
  kubernetes:
    version: 1.24.2
  purpose: evaluation
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    timeWindow:
      begin: 040000+0200
      end: 050000+0200
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    schedules:
      - start: 00 17 * * 1,2,3,4,5
        location: Europe/Berlin
