config:
  gardenClientConnection:
    kubeconfigSecret:
      name: gardenlet-kubeconfig
      namespace: garden
    bootstrapKubeconfig:
      name: gardenlet-kubeconfig-bootstrap
      namespace: garden
      kubeconfig: |
        apiVersion: v1
        kind: Config
        current-context: gardenlet-bootstrap
        clusters:
        - cluster:
            insecure-skip-tls-verify: true
            server: https://gardener-local-ha-single-zone-control-plane:6443
          name: default
        contexts:
        - context:
            cluster: default
            user: gardenlet-bootstrap
          name: gardenlet-bootstrap
        users:
        - name: gardenlet-bootstrap
          user:
            token: 07401b.f395accd246ae52d
  seedConfig:
    metadata:
      name: local-ha-single-zone
    spec:
      provider:
        zones:
        - "0"
      ingress:
        domain: ingress.local-ha-single-zone.seed.local.gardener.cloud
      secretRef:
        name: seed-local-ha-single-zone
