config:
  gardenClientConnection:
    bootstrapKubeconfig:
      kubeconfig: |
        apiVersion: v1
        kind: Config
        current-context: gardenlet-bootstrap
        clusters:
        - cluster:
            insecure-skip-tls-verify: true
            # The first kind cluster is used as the garden cluster.
            # Hence, overwrite the in-cluster kubernetes service with the kind node's hostname as the garden cluster address.
            # Note that this doesn't work in IPv6 single-stack kind clusters,
            # ref https://github.com/kubernetes-sigs/kind/issues/3114
            # I.e., the local setup with two seeds for testing control plane migration is not supported in combination with IPv6.
            server: https://gardener-local-control-plane:6443
          name: default
        contexts:
        - context:
            cluster: default
            user: gardenlet-bootstrap
          name: gardenlet-bootstrap
        users:
        - name: gardenlet-bootstrap
          user:
            token: 07401c.f395accd246ae52d
  seedConfig:
    metadata:
      name: local2
    spec:
      ingress:
        domain: ingress.local2.seed.local.gardener.cloud
      secretRef:
        name: seed-local2
