apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-10-04T06:47:26Z"
    generation: 1
    labels:
      component: kube-state-metrics
      gardener.cloud/role: monitoring
      type: shoot
    name: kube-state-metrics
    namespace: shoot--local--local
    resourceVersion: "9477"
    uid: c4ffead9-31ad-47eb-be89-1a11fd8ff0cf
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        component: kube-state-metrics
        type: shoot
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: kube-state-metrics
          gardener.cloud/role: monitoring
          networking.gardener.cloud/from-prometheus: allowed
          networking.gardener.cloud/to-dns: allowed
          networking.gardener.cloud/to-shoot-apiserver: allowed
          type: shoot
      spec:
        automountServiceAccountToken: false
        containers:
        - args:
          - --port=8080
          - --telemetry-port=8081
          - --resources=daemonsets,deployments,nodes,pods,statefulsets,verticalpodautoscalers,replicasets
          - --namespaces=kube-system
          - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
          - --metric-labels-allowlist=nodes=[*]
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: kube-state-metrics
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
            name: kubeconfig
            readOnly: true
        dnsPolicy: ClusterFirst
        priorityClassName: gardener-system-100
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: kubeconfig
          projected:
            defaultMode: 420
            sources:
            - secret:
                items:
                - key: kubeconfig
                  path: kubeconfig
                name: generic-token-kubeconfig-4fbc20b5
                optional: false
            - secret:
                items:
                - key: token
                  path: token
                name: shoot-access-kube-state-metrics
                optional: false
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-10-04T06:47:26Z"
      lastUpdateTime: "2022-10-04T06:47:26Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-10-04T06:47:26Z"
      lastUpdateTime: "2022-10-04T06:47:56Z"
      message: ReplicaSet "kube-state-metrics-7fddf6bbfc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
