global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    seed: local
alerting:
  alert_relabel_configs:
  - source_labels: [ignoreAlerts]
    separator: ;
    regex: "true"
    replacement: $1
    action: drop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_component]
      separator: ;
      regex: alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_service_label_role]
      separator: ;
      regex: monitoring
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: metrics
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - garden
rule_files:
- /etc/prometheus/rules/*.yaml
scrape_configs:
- job_name: shoot-prometheus
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{__name__="shoot:availability"}'
    - '{__name__=~"shoot:(.+):(.+)"}'
    - '{__name__="ALERTS"}'
    - '{__name__="prometheus_tsdb_lowest_timestamp"}'
    - '{__name__="prometheus_tsdb_storage_blocks_bytes"}'
    - '{__name__="kubeproxy_network_latency:quantile"}'
    - '{__name__="kubeproxy_sync_proxy:quantile"}'
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_endpoints_name,
      __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: shoot-(.+);prometheus-web;metrics
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: prometheus
  honor_timestamps: true
  params:
    match[]:
    - '{__name__=~"seed:(.+):(.+)"}'
    - '{job="kube-state-metrics",namespace=~"garden|extension-.+"}'
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_endpoints_name,
      __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: garden;prometheus-web;web
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: alertmanager
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoints_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: alertmanager;cluster
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^()$
    replacement: $1
    action: keep
  - source_labels: [namespace]
    separator: ;
    regex: ^garden$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - garden
- job_name: loki
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: loki;metrics
    replacement: $1
    action: keep
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(loki_ingester_blocks_per_chunk_sum|loki_ingester_blocks_per_chunk_count|loki_ingester_chunk_age_seconds_sum|loki_ingester_chunk_age_seconds_count|loki_ingester_chunk_bounds_hours_sum|loki_ingester_chunk_bounds_hours_count|loki_ingester_chunk_compression_ratio_sum|loki_ingester_chunk_compression_ratio_count|loki_ingester_chunk_encode_time_seconds_sum|loki_ingester_chunk_encode_time_seconds_count|loki_ingester_chunk_entries_sum|loki_ingester_chunk_entries_count|loki_ingester_chunk_size_bytes_sum|loki_ingester_chunk_size_bytes_count|loki_ingester_chunk_utilization_sum|loki_ingester_chunk_utilization_count|loki_ingester_memory_chunks|loki_ingester_received_chunks|loki_ingester_samples_per_chunk_sum|loki_ingester_samples_per_chunk_count|loki_ingester_sent_chunks|loki_panic_total|loki_logql_querystats_duplicates_total|loki_logql_querystats_ingester_sent_lines_total|prometheus_target_scrapes_sample_out_of_order_total)$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - garden
- job_name: fluent-bit
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - separator: ;
    regex: (.*)
    target_label: __metrics_path__
    replacement: /api/v1/metrics/prometheus
    action: replace
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: fluent-bit;metrics
    replacement: $1
    action: keep
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(fluentbit_input_bytes_total|fluentbit_input_records_total|fluentbit_output_proc_bytes_total|fluentbit_output_proc_records_total|fluentbit_output_errors_total|fluentbit_output_retries_total|fluentbit_output_retries_failed_total|fluentbit_filter_add_records_total|fluentbit_filter_drop_records_total)$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - garden
- job_name: fluent-bit-output-plugin
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: fluent-bit;metrics-plugin
    replacement: $1
    action: keep
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(promtail_dropped_entries_total|fluentbit_loki_gardener_errors_total|fluentbit_loki_gardener_logs_without_metadata_total|fluentbit_loki_gardener_incoming_logs_total|fluentbit_loki_gardener_incoming_logs_with_endpoint_total|fluentbit_loki_gardener_forwarded_logs_total|fluentbit_loki_gardener_dropped_logs_total)$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - garden
- job_name: istiod
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name,
      __meta_kubernetes_namespace]
    separator: ;
    regex: istiod;metrics;istio-system
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(galley_validation_failed|galley_validation_passed|go_goroutines|go_memstats_alloc_bytes|go_memstats_heap_alloc_bytes|go_memstats_heap_inuse_bytes|go_memstats_heap_sys_bytes|go_memstats_stack_inuse_bytes|istio_build|pilot_conflict_inbound_listener|pilot_conflict_outbound_listener_http_over_current_tcp|pilot_conflict_outbound_listener_tcp_over_current_http|pilot_conflict_outbound_listener_tcp_over_current_tcp|pilot_k8s_cfg_events|pilot_proxy_convergence_time_bucket|pilot_services|pilot_total_xds_internal_errors|pilot_total_xds_rejects|pilot_virt_services|pilot_xds|pilot_xds_cds_reject|pilot_xds_eds_reject|pilot_xds_lds_reject|pilot_xds_push_context_errors|pilot_xds_pushes|pilot_xds_rds_reject|pilot_xds_write_timeout|process_cpu_seconds_total|process_open_fds|process_resident_memory_bytes|process_virtual_memory_bytes)$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - istio-system
- job_name: istio-ingressgateway
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /stats/prometheus
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name,
      __meta_kubernetes_namespace]
    separator: ;
    regex: istio-ingressgateway;status-port;istio-ingress
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_ip]
    separator: ;
    regex: (.+)
    target_label: __address__
    replacement: ${1}:15020
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(envoy_cluster_upstream_cx_active|envoy_cluster_upstream_cx_connect_fail|envoy_cluster_upstream_cx_total|envoy_cluster_upstream_cx_tx_bytes_total|envoy_server_hot_restart_epoch|go_goroutines|go_memstats_alloc_bytes|go_memstats_heap_alloc_bytes|go_memstats_heap_inuse_bytes|go_memstats_heap_sys_bytes|go_memstats_stack_inuse_bytes|istio_build|istio_request_bytes_bucket|istio_request_bytes_sum|istio_request_duration_milliseconds_bucket|istio_request_duration_seconds_bucket|istio_requests_total|istio_response_bytes_bucket|istio_response_bytes_sum|istio_tcp_connections_closed_total|istio_tcp_connections_opened_total|istio_tcp_received_bytes_total|istio_tcp_sent_bytes_total|process_cpu_seconds_total|process_open_fds|process_resident_memory_bytes|process_virtual_memory_bytes)$
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - istio-ingress

