apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: local
spec:
  backup:
    provider: local
    region: local
    secretRef:
      name: seed-local
      namespace: garden
  provider:
    type: local
    region: local
  dns:
    provider:
      type: local
      secretRef:
        name: internal-domain-local
        namespace: garden
  ingress:
    domain: ingress.local.seed.local.gardener.cloud
    controller:
      kind: nginx
  secretRef:
    name: seed-local
    namespace: garden
  networks:
    nodes: 172.19.0.0/16
    pods: 10.1.0.0/16
    services: 10.2.0.0/16
    shootDefaults:
      pods: 10.3.0.0/16
      services: 10.4.0.0/16
  settings:
    dependencyWatchdog:
      probe:
        enabled: false
    excessCapacityReservation:
      enabled: false
    ownerChecks:
      enabled: false
    scheduling:
      visible: true
    shootDNS:
      enabled: true
    verticalPodAutoscaler:
      enabled: true
