{{- if and .Values.global.apiserver.enabled .Values.global.apiserver.workloadIdentity.token.signingKey.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-apiserver-workload-identity
  namespace: garden
  labels:
    app: gardener
    role: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.key: {{ .Values.global.apiserver.workloadIdentity.token.signingKey.tls.key | b64enc }}
{{- end }}
