{{- if .Values.global.apiserver.vpa }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: gardener-apiserver-vpa
  namespace: garden
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: gardener-apiserver
  updatePolicy:
    updateMode: Auto
{{- end }}