{{- if .Values.global.config.sourceClientConnection.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-source-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
type: Opaque
data:
  kubeconfig: {{ b64enc .Values.global.config.sourceClientConnection.kubeconfig }}
{{- end }}
