{{- if and .Values.global.config.server.webhooks.certificate .Values.global.config.server.webhooks.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc .Values.global.config.server.webhooks.certificate }}
  tls.key: {{ b64enc .Values.global.config.server.webhooks.privateKey }}
{{- end }}
