{{- if .Values.global.config.controllers.rootCAPublisher.rootCACertificate }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-root-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
type: kubernetes.io/tls
data:
  ca.crt: {{ b64enc .Values.global.config.controllers.rootCAPublisher.rootCACertificate }}
{{- end }}
