{{- if not .Values.global.config.sourceClientConnection.kubeconfig }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
{{- end }}
