apiVersion: v1
kind: Service
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.global.config.server.metrics.port }}
    protocol: TCP
  - name: health
    port: {{ .Values.global.config.server.healthProbes.port }}
    protocol: TCP
  - name: server
    port: 443
    targetPort: {{ .Values.global.config.server.webhooks.port }}
    protocol: TCP
  selector:
    app: gardener
    role: resource-manager
