description: HVPAConfigurationHPA contains HPA related configuration for the HVPA
  of the Gardener Extension API server
properties:
  maxReplicas:
    description: MaxReplicas is the maximum number of replicas. Defaults to 4.
    format: int32
    type: integer
  minReplicas:
    description: MinReplicas is the minimum number of replicas. Defaults to 1.
    format: int32
    type: integer
  targetAverageUtilizationCpu:
    description: 'TargetAverageUtilizationCpu is the average CPU utilization targeted
      by the HPA component of the HVPA Defaults to: 80'
    format: int32
    type: integer
  targetAverageUtilizationMemory:
    description: 'TargetAverageUtilizationMemory is the average memory utilization
      targeted by the HPA component of the HVPA Defaults to: 80'
    format: int32
    type: integer
type: object
