description: 'APIServerAuditConfiguration contains audit logging configuration For
  more information, please see: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/'
properties:
  dynamicConfiguration:
    description: DynamicConfiguration is used to enable dynamic auditing before v1.19
      via API server flag --audit-dynamic-configuration. This feature also requires
      the DynamicAuditing feature flag to be set.
    type: boolean
  log:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.APIServerAuditLogBackend.yaml
    description: 'Log configures the Log backend for audit events This is enabled
      with a default policy logging to the local filesystem For more information,
      please see here: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#log-backend'
  policy:
    $ref: blueprint://schema/io.k8s.apiserver.pkg.apis.audit.v1.Policy.yaml
    description: 'Policy contains the audit policy for the Gardener API Server. For
      more information, please see here: https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/#audit-k8s-io-v1-Policy'
  webhook:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.APIServerAuditWebhookBackend.yaml
    description: 'Webhook contains configuration for the webhook audit backend for
      the Gardener API server For more information, please see: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#webhook-backend'
type: object
