description: APIServerWatchCacheConfiguration fine tunes the watch cache size for
  different resources watched by the Gardener API Server. These are mostly, but not
  limited to, resources from Gardener resource groups e.g core.gardener.cloud. Some
  resources (replicationcontrollers, endpoints, nodes, pods, services, apiservices.apiregistration.k8s.io)
  have system defaults set by heuristics, others default to 'defaultSize'.
properties:
  defaultSize:
    description: DefaultSize is the default watch cache size
    format: int32
    type: integer
  resources:
    description: Resources contains a list of configurations of the watch cache sizes
    items:
      $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.WatchCacheSizeResource.yaml
      default: {}
    type: array
type: object
