description: CommonDeploymentConfiguration contains common deployment configurations
  for multiple Gardener components
properties:
  podAnnotations:
    additionalProperties:
      default: ""
      type: string
    description: PodAnnotations are additional annotations on the pods.
    type: object
  podLabels:
    additionalProperties:
      default: ""
      type: string
    description: PodLabels are additional labels on the pods.
    type: object
  replicaCount:
    description: 'ReplicaCount is the number of replicas. Default: 1.'
    format: int32
    type: integer
  resources:
    $ref: blueprint://schema/io.k8s.api.core.v1.ResourceRequirements.yaml
    description: Resources are compute resources required by the container.
  serviceAccountName:
    description: ServiceAccountName is the name of the ServiceAccount to create and
      mount into the pod.
    type: string
  vpa:
    description: 'VPA specifies whether to enable VPA for the deployment. Default:
      false.'
    type: boolean
type: object
