description: APIServerDeploymentConfiguration contains certain configurations for
  the deployment of the Gardener Extension API server
properties:
  hvpa:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.HVPAConfiguration.yaml
    description: Hvpa contains configurations for the HVPA of the Gardener Extension
      API server Please note that VPA has to be disabled in order to use HVPA
  livenessProbe:
    $ref: blueprint://schema/io.k8s.api.core.v1.Probe.yaml
    description: |-
      LivenessProbe allows to overwrite the default liveness probe Defaults:
       initialDelaySeconds: 15
       periodSeconds: 10
       successThreshold: 1
       failureThreshold: 3
       timeoutSeconds: 15
  minReadySeconds:
    description: MinReadySeconds allows to overwrite the default minReadySeconds field
      Defaults to 30
    format: int32
    type: integer
  podAnnotations:
    additionalProperties:
      default: ""
      type: string
    description: PodAnnotations are additional annotations on the pods.
    type: object
  podLabels:
    additionalProperties:
      default: ""
      type: string
    description: PodLabels are additional labels on the pods.
    type: object
  readinessProbe:
    $ref: blueprint://schema/io.k8s.api.core.v1.Probe.yaml
    description: |-
      LivenessProbe allows to overwrite the default readiness probe Defaults:
       initialDelaySeconds: 15
       periodSeconds: 10
       successThreshold: 1
       failureThreshold: 3
       timeoutSeconds: 15
  replicaCount:
    description: 'ReplicaCount is the number of replicas. Default: 1.'
    format: int32
    type: integer
  resources:
    $ref: blueprint://schema/io.k8s.api.core.v1.ResourceRequirements.yaml
    description: Resources are compute resources required by the container.
  serviceAccountName:
    description: ServiceAccountName is the name of the ServiceAccount to create and
      mount into the pod.
    type: string
  vpa:
    description: 'VPA specifies whether to enable VPA for the deployment. Default:
      false.'
    type: boolean
type: object
