description: ControllerManagerComponentConfiguration contains the component configuration
  for the Gardener controller manager
properties:
  config:
    $ref: blueprint://schema/io.k8s.apimachinery.pkg.runtime.RawExtension.yaml
    default: {}
    description: Config specifies values for the Gardener Controller Manager component
      configuration Please see example/20-componentconfig-gardener-controller-manager.yaml
      for what can be configured here
  tls:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.TLSServer.yaml
    description: TLS configures the HTTPS server of the Gardener Controller Manager
      uses http for /healthz endpoint, optionally serves HTTPS for metrics. If left
      empty, generates a certificate signed by the CA that also signs the TLS serving
      certificates of the Gardener API server.
type: object
