description: 'HVPAConfiguration contains configurations for the HVPA of the Gardener
  Extension API server For more information on HVPA, please see here: https://github.com/gardener/hvpa-controller'
properties:
  enabled:
    description: 'Enabled configures whether to setup hvpa for the Gardener Extension
      API server or not Default: false'
    type: boolean
  hvpaConfigurationHPA:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.HVPAConfigurationHPA.yaml
    description: HVPAConfigurationHPA contains the HPA specific configuration for
      HVPA
  hvpaConfigurationVPA:
    $ref: blueprint://schema/com.github.gardener.gardener.landscaper.pkg.controlplane.apis.imports.v1alpha1.HVPAConfigurationVPA.yaml
    description: HVPAConfigurationVPA contains the VPA specific configuration for
      HVPA
  maintenanceTimeWindow:
    $ref: blueprint://schema/com.github.gardener.hvpa-controller.api.v1alpha1.MaintenanceTimeWindow.yaml
    description: MaintenanceWindow defines the time window when HVPA is allowed to
      act
type: object
