environment: skaffold # skaffold|local
# TODO(ary1992): Update to 1.27.1 after the merge of https://github.com/gardener/gardener/pull/7883 has been merged and released (after 1.71 has been released).
image: kindest/node:v1.26.3

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddresses:
      - 127.0.0.1
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true
  hostname: garden.local.gardener.cloud

networking:
  ipFamily: ipv4
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
