# TODO(oliver-goetz): Update to 1.28.0 after the merge of https://github.com/gardener/gardener/pull/8479 has been merged and released (after 1.80 has been released).
image: kindest/node:v1.27.1

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
  nginxIngress:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddresses:
      - 127.0.0.1
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true

networking:
  ipFamily: ipv4
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16

#workers:
#- zone: "1"
#- zone: "2"
