environment: skaffold # skaffold|local
image: kindest/node:v1.24.7

gardener:
  apiserverRelay:
    deployed: false
  controlPlane:
    deployed: true
  seed:
    deployed: true
    istio:
      listenAddressDefault: 127.0.0.1
      listenAddressZone0: 127.0.0.10
      listenAddressZone1: 127.0.0.11
      listenAddressZone2: 127.0.0.12
  repositoryRoot: "."
  garden:
    deployed: false

backupBucket:
  deployed: true

registry:
  deployed: true
  hostname: gardener-local-control-plane

#workers:
#- zone: "1"
#- zone: "2"
