{{- define "shoot-cloud-config.execution-script.rendered" -}}
{{- include "shoot-cloud-config.execution-script" .Values -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.worker.secretName }}
  namespace: kube-system
  annotations:
    checksum/data-script: {{ include "shoot-cloud-config.execution-script.rendered" . | sha256sum }}
data:
  script: {{ include "shoot-cloud-config.execution-script.rendered" . | b64enc }}
