apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox-exporter
spec:
  type: ClusterIP
  ports:
  - name: probe
    port: 9115
    protocol: TCP
  selector:
    app: blackbox-exporter