apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: prometheus
    role: monitoring
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: {{include "statefulsetversion" .}}
kind: StatefulSet
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: monitoring
    app: prometheus
    role: monitoring
spec:
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: prometheus
      role: monitoring
  serviceName: prometheus
  template:
    metadata:
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        garden.sapcloud.io/role: monitoring
        app: prometheus
        role: monitoring
    spec:
      # used to talk to Seed's API server.
      serviceAccountName: prometheus
      initContainers:
      - name: set-iptable-rules
        image: {{ index .Values.images "alpine" }}
        command: ['/bin/sh', '-c', 'apk update && apk add iptables && iptables -A INPUT -i tun0 -p icmp -j ACCEPT && iptables -A INPUT -i tun0 -m state --state NEW -j DROP']
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      containers:
      - name: prometheus
        image: {{ index .Values.images "prometheus" }}
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/prometheus/config/prometheus.yaml
        - --storage.tsdb.path=/var/prometheus/data
        - --storage.tsdb.no-lockfile
        - --storage.tsdb.retention.time=180h
        - --web.route-prefix=/
        - --web.enable-lifecycle
        - --web.listen-address=0.0.0.0:{{ .Values.port }}
        - --web.external-url=https://{{ .Values.ingress.host }}
        # Since v2.0.0-beta.3 prometheus runs as nobody user (fsGroup 65534/runAsUser 0)
        # data volume needs to be mounted with the same permissions,
        # otherwise we will have Permission denied problems
        securityContext:
          runAsUser: 0
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: {{ .Values.port }}
            scheme: HTTP
          failureThreshold: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /-/ready
            port: {{ .Values.port }}
            scheme: HTTP
          failureThreshold: 120
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
{{- if .Values.vpa.enabled }}
          requests:
            cpu: 30m
            memory: 500Mi
{{- else }}
{{- include "util-templates.resource-quantity" .Values | indent 10 -}}
{{ end }}
        volumeMounts:
        - mountPath: /srv/kubernetes/prometheus-kubelet
          name: prometheus-kubelet
        - mountPath: /srv/kubernetes/etcd/ca
          name: ca-etcd
        - mountPath: /srv/kubernetes/etcd/client
          name: etcd-client-tls
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
          readOnly: true
        - mountPath: /var/prometheus/data
          name: prometheus-db
          subPath: prometheus-
        # we mount the Shoot cluster's CA and certs
        - mountPath: /etc/prometheus/seed
          name: prometheus-kubeconfig
      - name: prometheus-config-reloader
        image: {{ index .Values.images "configmap-reloader" }}
        imagePullPolicy: IfNotPresent
        args:
        - -webhook-url=http://localhost:9090/-/reload
        - -volume-dir=/etc/prometheus/config
        - -volume-dir=/etc/prometheus/rules
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
          readOnly: true
        - mountPath: /etc/prometheus/rules
          name: rules
      - image: {{ index .Values.images "vpn-seed" }}
        imagePullPolicy: IfNotPresent
        name: vpn-seed
        env:
        - name: OPENVPN_PORT
          value: "4314"
        ports:
        - name: https
          containerPort: 1194
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv/secrets/vpn-seed
          name: vpn-seed
        - mountPath: /srv/secrets/tlsauth
          name: vpn-seed-tlsauth
        - mountPath: /srv/auth
          name: kube-apiserver-basic-auth
      terminationGracePeriodSeconds: 300
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: prometheus-config
      - name: rules
        configMap:
          defaultMode: 420
          name: prometheus-rules
      - name: vpn-seed
        secret:
          secretName: vpn-seed
      - name: vpn-seed-tlsauth
        secret:
          secretName: vpn-seed-tlsauth
      - name: shoot-ca
        secret:
          defaultMode: 420
          secretName: ca
      - name: ca-etcd
        secret:
          secretName: ca-etcd
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls
      - name: kube-apiserver-basic-auth
        secret:
          secretName: kube-apiserver-basic-auth
      - name: prometheus-kubeconfig
        secret:
          secretName: prometheus
      - name: prometheus-kubelet
        secret:
          secretName: prometheus-kubelet
  volumeClaimTemplates:
  - metadata:
      name: prometheus-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage }}
