apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ../../seed-kind-ha-single-zone/local

patchesJson6902:
- target:
    group: core.gardener.cloud
    version: v1beta1
    kind: Seed
    name: local-ha-single-zone
  path: patch-seed.yaml