apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: seed-local
  namespace: garden
  files:
  - kubeconfig

resources:
- cloudprofile.yaml
- controller-registration.yaml
- project.yaml
- secretbinding.yaml
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.23.0/example/controller-registration.yaml

patchesStrategicMerge:
- patch-controller-registrations.yaml
