apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:apiserver-proxy
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if semverCompare "< 1.23-0" .Capabilities.KubeVersion.GitVersion }}
  name: gardener.cloud:psp:kube-system:apiserver-proxy
  {{- else }}
  name: gardener.cloud:psp:privileged
  {{- end }}
subjects:
- kind: ServiceAccount
  name: apiserver-proxy
  namespace: kube-system
