{{- if and (semverCompare ">= 1.12" .Values.global.kubernetesVersion) (semverCompare "< 1.14" .Values.global.kubernetesVersion) }}
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: system:controller:kube-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: User
  name: system:kube-controller-manager
---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: system:controller:kube-controller-manager:auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: User
  name: system:kube-controller-manager
{{- end }}
