# This file contains a minimal Control Plane import configuration.
apiVersion: controlplane.gardener.landscaper.gardener.cloud/v1alpha1
kind: Imports
runtimeCluster:
  apiVersion: landscaper.gardener.cloud/v1alpha1
  kind: Target
  spec:
    type: landscaper.gardener.cloud/kubernetes-cluster
    config:
      kubeconfig: |
        ---
        apiVersion:...
        # here goes the kubeconfig of the runtime cluster


internalDomain:
  provider: aws-route53
  domain: internal.test.domain
  credentials:
    AWS_ACCESS_KEY_ID: <very-secret-base64>
    AWS_SECRET_ACCESS_KEY: <very-secret-base64>

etcdUrl: "virtual-garden-etcd-main-client.garden.svc:2379"
# if etcd requires client authentication:
#etcdCaBundle: |
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----

#etcdClientCert: |
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----

#etcdClientKey: |
#  -----BEGIN RSA PRIVATE KEY-----
#  ...
#  -----END RSA PRIVATE KEY-----

# specify when the virtual garden option is enabled
#virtualGardenCluster:
#  apiVersion: landscaper.gardener.cloud/v1alpha1
#  kind: Target
#  spec:
#    type: landscaper.gardener.cloud/kubernetes-cluster
#    config:
#      kubeconfig: |
#        ---
#        apiVersion:...
#        # here goes the kubeconfig of the virtual-garden cluster

#virtualGarden:
#  enabled: false
#  clusterIP: "100.64.10.10"
