apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yaml: |
    # All services in the {{ .Release.Namespace }} and that are annotated with
    # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
    # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need to set this to `https` & most likely set the `tls_config` of the scrape config.
    # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
    # * `prometheus.io/port`: If the metrics are exposed on a different port to the service then set this appropriately. Use this when multiple ports are avaible by the pod.
    # * `prometheus.io/name`: job name label to be applied to all metrics from that service.
    # take note that there is a limit of 500 samples per target

    global:
      evaluation_interval: 1m
      scrape_interval: 1m
    scrape_configs:
{{- if .Values.additionalScrapeConfigs }}
{{ toString .Values.additionalScrapeConfigs | indent 4 }}
{{- end }}
