trustDomain: cluster.local
image: to-be-injected-by-imagevector
labels:
  app: istiod
  istio: pilot
deployNamespace: false
priorityClassName: gardener-system-critical
ports:
  https: 10250
portsNames:
  metrics: metrics
serviceName: istiod

# TODO(rfranzke): To be removed after v1.71 got released. Only required to move istiod assets to separate ManagedResource.
ignoreMode: false
