{{- if .Values.global.gardenlet.enabled }}
### Istio releated rules. Required even when ManagedIstio/APIServerSNI are not enabled due to clean-up reconciliations.
---
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:system:gardenlet:managed-istio
  namespace: "{{ required ".Values.global.gardenlet.config.sni.ingress.namespace is required" .Values.global.gardenlet.config.sni.ingress.namespace }}"
  labels:
    gardener.cloud/role: gardenlet
    app: gardener
    role: gardenlet
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gardener.cloud:system:gardenlet:managed-istio
subjects:
- kind: ServiceAccount
  name: "{{ required ".Values.global.gardenlet.serviceAccountName is required" .Values.global.gardenlet.serviceAccountName }}"
  namespace: garden
{{- end }}
