{{- if .Values.global.apiserver.enabled }}
apiVersion: {{ include "apiserviceversion" . }}
kind: APIService
metadata:
  name: v1beta1.garden.sapcloud.io
  labels:
    app: gardener
    role: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  insecureSkipTLSVerify: {{ .Values.global.apiserver.insecureSkipTLSVerify }}
  {{- if not .Values.global.apiserver.insecureSkipTLSVerify }}
  caBundle: {{ required ".Values.global.apiserver.caBundle is required" (b64enc .Values.global.apiserver.caBundle) }}
  {{- end }}
  group: garden.sapcloud.io
  version: v1beta1
  groupPriorityMinimum: 10
  versionPriority: 10
  service:
    name: gardener-apiserver
    namespace: garden
{{- end }}
