apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../seed-kind-ha/local

patchesJson6902:
- target:
    group: core.gardener.cloud
    version: v1beta1
    kind: Seed
    name: local-ha
  path: patch-seed.yaml
