apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: auditlog
spec:
  groups:
  - name: auditlog
    rules:
    - alert: TooManyAuditlogFailures
      expr: |
        ( sum by (job) (
              rate(
                apiserver_audit_error_total{plugin="webhook"}[5m]
              )
          )
          /
          sum by (job) (
              rate(
                apiserver_audit_event_total[5m]
              )
          )
        ) > 0.02
      for: 10m
      labels:
        severity: warning
        topology: garden
      annotations:
        summary: >-
          The {{$labels.job}} server in landscape {{$externalLabels.landscape}}
          has too many failed attempts to log audit events.
        description: >-
          The API server's cumulative failure rate in logging audit events is
          greater than 2%.
