apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: recording
spec:
  groups:
  - name: recording.rules
    rules:
    ### API latency ###
    - record: apiserver_latency_seconds:quantile
      expr: |
        histogram_quantile(
          0.99,
          rate(
            apiserver_request_duration_seconds_bucket[5m]
          )
        )
      labels:
        quantile: "0.99"

    - record: apiserver_latency_seconds:quantile
      expr: |
        histogram_quantile(
          0.9,
          rate(
            apiserver_request_duration_seconds_bucket[5m]
          )
        )
      labels:
        quantile: "0.9"

    - record: apiserver_latency_seconds:quantile
      expr: |
        histogram_quantile(
          0.5,
          rate(
            apiserver_request_duration_seconds_bucket[5m]
          )
        )
      labels:
        quantile: "0.5"
