apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../seed-base

secretGenerator:
- name: seed-local2
  namespace: garden
  files:
  - kubeconfig

patchesJson6902:
- target:
    group: core.gardener.cloud
    version: v1beta1
    kind: Seed
    name: local
  path: patch-seed.yaml