apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: gardener.cloud:psp:kube-system:node-exporter
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.node-exporter
  resources:
  - podsecuritypolicies
  verbs:
  - use
