apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:node-exporter
  namespace: kube-system
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if semverCompare "< 1.23-0" .Capabilities.KubeVersion.GitVersion }}
  name: gardener.cloud:psp:kube-system:node-exporter
  {{- else }}
  name: gardener.cloud:psp:privileged
  {{- end }}
subjects:
- kind: ServiceAccount
  name: node-exporter
  namespace: kube-system
