# TODO(rfranzke): Delete this Helm chart in a future version.
---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:kube-proxy
  annotations:
    resources.gardener.cloud/mode: Ignore
