apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: gardener.kube-system.kube-proxy
spec:
  privileged: true
  volumes:
  - hostPath
  - secret
  - configMap
  hostNetwork: true
  hostPorts:
  - min: {{ .Values.ports.metrics }}
    max: {{ .Values.ports.metrics }}
  allowedHostPaths:
  - pathPrefix: /usr/share/ca-certificates
  - pathPrefix: /var/run/dbus/system_bus_socket
  - pathPrefix: /lib/modules
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
