apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  upstream: none

resources:
- ../base

patches:
- target:
    group: apps
    kind: Deployment
    name: registry
  patch: |
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /etc/gardener/local-registry/localhost
