apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-apiserver.auditConfig.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
  audit-policy.yaml: |-
    ---
{{ include "kube-apiserver.auditConfigAuditPolicy" . | indent 4 }}
