apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-apiserver.admissionConfig.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "kube-apiserver.admissionConfig.data" . | indent 2 }}
