{{- if .Values.reversedVPN.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-apiserver.egressSelector.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "kube-apiserver.egressSelector.data" . | indent 2 }}
{{- end }}
