      containers:
        command:
        {{- if semverCompare "< 1.17" .Values.kubernetesVersion }}
        - /hyperkube
        - kube-apiserver
        {{- else }}
        - /usr/local/bin/kube-apiserver
        {{- end }}
        {{- if .Values.reversedVPN.enabled }}
        - --egress-selector-config-file=/etc/kubernetes/egress/egress-selector-configuration.yaml
        {{- end}}
        - --enable-admission-plugins={{ include "kube-apiserver.admissionPlugins" . | trimSuffix "," }}
        - --admission-control-config-file={{ include "kube-apiserver.admissionPluginConfigFileDir" . }}/admission-configuration.yaml
        - --allow-privileged=true
        - --anonymous-auth={{ .Values.enableAnonymousAuthentication }}
        - --audit-log-path=/var/lib/audit.log
        - --audit-policy-file=/etc/kubernetes/audit/audit-policy.yaml
        - --audit-log-maxsize=100
        - --audit-log-maxbackup=5
        - --authorization-mode=Node,RBAC
        {{- if .Values.sni.enabled }}
        - --advertise-address={{ .Values.sni.advertiseIP }}
        {{- end }}
        {{- if .Values.enableBasicAuthentication }}
        - --basic-auth-file=/srv/kubernetes/auth/basic_auth.csv
        {{- end }}
        - --client-ca-file=/srv/kubernetes/ca/ca.crt
        - --enable-aggregator-routing=true
        - --enable-bootstrap-token-auth=true
        {{- include "kube-apiserver.watchCacheSizes" . | indent 8 }}
        - --http2-max-streams-per-connection=1000
        - --etcd-cafile=/srv/kubernetes/etcd/ca/ca.crt
        - --etcd-certfile=/srv/kubernetes/etcd/client/tls.crt
        - --etcd-keyfile=/srv/kubernetes/etcd/client/tls.key
        - --etcd-servers=https://etcd-main-client:{{ .Values.etcdServicePort }}
        - --etcd-servers-overrides=/events#https://etcd-events-client:{{ .Values.etcdServicePort }}
        {{- if .Values.enableEtcdEncryption }}
        - --encryption-provider-config=/etc/kubernetes/etcd-encryption-secret/encryption-configuration.yaml
        {{- end }}
        {{- include "kube-apiserver.featureGates" . | trimSuffix "," | indent 8 }}
        - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
        - --kubelet-client-certificate=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.crt
        - --kubelet-client-key=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.key
        - --insecure-port=0
        {{- include "kube-apiserver.oidcConfig" . | indent 8 }}
        {{- if semverCompare ">= 1.16" .Values.kubernetesVersion }}
        - --livez-grace-period=1m
        {{- end }}
        {{- if .Values.maxNonMutatingRequestsInflight }}
        - --max-requests-inflight={{ .Values.maxNonMutatingRequestsInflight }}
        {{- end }}
        {{- if .Values.maxMutatingRequestsInflight }}
        - --max-mutating-requests-inflight={{ .Values.maxMutatingRequestsInflight }}
        {{- end }}
        - --profiling=false
        - --proxy-client-cert-file=/srv/kubernetes/aggregator/kube-aggregator.crt
        - --proxy-client-key-file=/srv/kubernetes/aggregator/kube-aggregator.key
        - --requestheader-client-ca-file=/srv/kubernetes/ca-front-proxy/ca.crt
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        {{- include "kube-apiserver.runtimeConfig" . | trimSuffix "," | indent 8 }}
        - --secure-port={{ required ".securePort is required" .Values.securePort }}
        - --service-cluster-ip-range={{ .Values.shootNetworks.services }}
        - --service-account-key-file=/srv/kubernetes/service-account-key/id_rsa
        {{- if semverCompare ">= 1.16" .Values.kubernetesVersion }}
        - --shutdown-delay-duration=15s
        {{- end }}
        {{- if .Values.externalHostname }}
        - --external-hostname={{ .Values.externalHostname }}
        {{- end }}
        - --token-auth-file=/srv/kubernetes/token/static_tokens.csv
        - --tls-cert-file=/srv/kubernetes/apiserver/kube-apiserver.crt
        - --tls-private-key-file=/srv/kubernetes/apiserver/kube-apiserver.key
        - --tls-cipher-suites={{ .Values.tlsCipherSuites | join "," }}
        {{- include "kube-apiserver.apiAudiences" . | indent 8 }}
        {{- include "kube-apiserver.serviceAccountConfig" . | indent 8 }}
        - --v=2
        volumeMounts:
        {{- if .Values.reversedVPN.enabled }}
        - name: kube-apiserver-http-proxy
          mountPath: /etc/srv/kubernetes/envoy
        - name: egress-selection-config
          mountPath: /etc/kubernetes/egress
        {{- end }}
        - name: audit-policy-config
          mountPath: /etc/kubernetes/audit
        - name: ca
          mountPath: /srv/kubernetes/ca
        - name: ca-etcd
          mountPath: /srv/kubernetes/etcd/ca
        - name: ca-front-proxy
          mountPath: /srv/kubernetes/ca-front-proxy
        - name: etcd-client-tls
          mountPath: /srv/kubernetes/etcd/client
        - name: kube-apiserver
          mountPath: /srv/kubernetes/apiserver
        - name: service-account-key
          mountPath: /srv/kubernetes/service-account-key
        {{- if .Values.enableBasicAuthentication }}
        - name: kube-apiserver-basic-auth
          mountPath: /srv/kubernetes/auth
        {{- end }}
        - name: static-token
          mountPath: /srv/kubernetes/token
        - name: kube-apiserver-kubelet
          mountPath: /srv/kubernetes/apiserver-kubelet
        - name: kube-aggregator
          mountPath: /srv/kubernetes/aggregator
        {{- if .Values.oidcConfig.caBundle }}
        - name: kube-apiserver-oidc-cabundle
          mountPath: /srv/kubernetes/oidc
        {{- end }}
        {{- if .Values.serviceAccountConfig }}
        {{- if .Values.serviceAccountConfig.signingKey }}
        - name: kube-apiserver-service-account-signing-key
          mountPath: /srv/kubernetes/service-account-signing-key
        {{- end }}
        {{- end }}
        - name: kube-apiserver-admission-config
          mountPath: {{ include "kube-apiserver.admissionPluginConfigFileDir" . }}
        {{- if .Values.enableEtcdEncryption }}
        - name: etcd-encryption-secret
          mountPath: /etc/kubernetes/etcd-encryption-secret
          readOnly: true
        {{- end }}
      volumes:
      - name: audit-policy-config
        configMap:
          name: {{ include "kube-apiserver.auditConfig.name" . }}
      - name: ca
        secret:
          secretName: ca
      - name: ca-etcd
        secret:
          secretName: ca-etcd
      - name: ca-front-proxy
        secret:
          secretName: ca-front-proxy
      - name: kube-apiserver
        secret:
          secretName: kube-apiserver
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls
      - name: service-account-key
        secret:
          secretName: service-account-key
      {{- if .Values.reversedVPN.enabled }}
      - name: kube-apiserver-http-proxy
        secret:
          secretName: kube-apiserver-http-proxy
      {{- end }}
      {{- if .Values.enableBasicAuthentication }}
      - name: kube-apiserver-basic-auth
        secret:
          secretName: kube-apiserver-basic-auth
      {{- end }}
      - name: static-token
        secret:
          secretName: static-token
      - name: kube-apiserver-kubelet
        secret:
          secretName: kube-apiserver-kubelet
      - name: kube-aggregator
        secret:
          secretName: kube-aggregator
      {{- if .Values.oidcConfig.caBundle }}
      - name: kube-apiserver-oidc-cabundle
        secret:
          secretName: {{ include "kube-apiserver.oidcCABundle.name" . }}
      {{- end }}
      {{- if .Values.serviceAccountConfig }}
      {{- if .Values.serviceAccountConfig.signingKey }}
      - name: kube-apiserver-service-account-signing-key
        secret:
          secretName: {{ include "kube-apiserver.serviceAccountSigningKeyConfig.name" . }}
      {{- end }}
      {{- end }}
      - name: kube-apiserver-admission-config
        configMap:
          name: {{ include "kube-apiserver.admissionConfig.name" . }}
      {{- if .Values.reversedVPN.enabled }}
      - name: egress-selection-config
        configMap:
          name: {{ include "kube-apiserver.egressSelector.name" . }}
      {{- end }}
      {{- if .Values.enableEtcdEncryption }}
      - name: etcd-encryption-secret
        secret:
          defaultMode: 420
          secretName: etcd-encryption-secret
      {{- end }}
