      containers:
        command:
        {{- if semverCompare "< 1.17" .Values.kubernetesVersion }}
        - /hyperkube
        - kube-apiserver
        {{- else }}
        - /usr/local/bin/kube-apiserver
        {{- end }}
        {{- if .Values.reversedVPN.enabled }}
        - --egress-selector-config-file=/etc/kubernetes/egress/egress-selector-configuration.yaml
        {{- end}}
        - --enable-admission-plugins={{ include "kube-apiserver.admissionPlugins" . | trimSuffix "," }}
        - --admission-control-config-file={{ include "kube-apiserver.admissionPluginConfigFileDir" . }}/admission-configuration.yaml
        - --allow-privileged=true
        - --anonymous-auth={{ .Values.enableAnonymousAuthentication }}
        - --audit-log-path=/var/lib/audit.log
        - --audit-policy-file=/etc/kubernetes/audit/audit-policy.yaml
        - --audit-log-maxsize=100
        - --audit-log-maxbackup=5
        - --authorization-mode=Node,RBAC
        {{- if .Values.sni.enabled }}
        - --advertise-address={{ .Values.sni.advertiseIP }}
        {{- end }}
        {{- if .Values.enableBasicAuthentication }}
        - --basic-auth-file=/srv/kubernetes/auth/basic_auth.csv
        {{- end }}
        - --client-ca-file=/srv/kubernetes/ca/ca.crt
        - --enable-aggregator-routing=true
        - --enable-bootstrap-token-auth=true
        {{- include "kube-apiserver.watchCacheSizes" . | indent 8 }}
        - --http2-max-streams-per-connection=1000
        - --etcd-cafile=/srv/kubernetes/etcd/ca/ca.crt
        - --etcd-certfile=/srv/kubernetes/etcd/client/tls.crt
        - --etcd-keyfile=/srv/kubernetes/etcd/client/tls.key
        - --etcd-servers=https://etcd-main-client:{{ .Values.etcdServicePort }}
        - --etcd-servers-overrides=/events#https://etcd-events-client:{{ .Values.etcdServicePort }}
        {{- if .Values.enableEtcdEncryption }}
        - --encryption-provider-config=/etc/kubernetes/etcd-encryption-secret/encryption-configuration.yaml
        {{- end }}
        {{- include "kube-apiserver.featureGates" . | trimSuffix "," | indent 8 }}
        - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
        - --kubelet-client-certificate=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.crt
        - --kubelet-client-key=/srv/kubernetes/apiserver-kubelet/kube-apiserver-kubelet.key
        - --insecure-port=0
        {{- include "kube-apiserver.oidcConfig" . | indent 8 }}
        {{- if semverCompare ">= 1.16" .Values.kubernetesVersion }}
        - --livez-grace-period=1m
        {{- end }}
        {{- if .Values.maxNonMutatingRequestsInflight }}
        - --max-requests-inflight={{ .Values.maxNonMutatingRequestsInflight }}
        {{- end }}
        {{- if .Values.maxMutatingRequestsInflight }}
        - --max-mutating-requests-inflight={{ .Values.maxMutatingRequestsInflight }}
        {{- end }}
        - --profiling=false
        - --proxy-client-cert-file=/srv/kubernetes/aggregator/kube-aggregator.crt
        - --proxy-client-key-file=/srv/kubernetes/aggregator/kube-aggregator.key
        - --requestheader-client-ca-file=/srv/kubernetes/ca-front-proxy/ca.crt
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        {{- include "kube-apiserver.runtimeConfig" . | trimSuffix "," | indent 8 }}
        - --secure-port={{ required ".securePort is required" .Values.securePort }}
        - --service-cluster-ip-range={{ .Values.shootNetworks.services }}
        - --service-account-key-file=/srv/kubernetes/service-account-key/id_rsa
        {{- if semverCompare ">= 1.16" .Values.kubernetesVersion }}
        - --shutdown-delay-duration=15s
        {{- end }}
        {{- if .Values.externalHostname }}
        - --external-hostname={{ .Values.externalHostname }}
        {{- end }}
        - --token-auth-file=/srv/kubernetes/token/static_tokens.csv
        - --tls-cert-file=/srv/kubernetes/apiserver/kube-apiserver.crt
        - --tls-private-key-file=/srv/kubernetes/apiserver/kube-apiserver.key
        - --tls-cipher-suites={{ .Values.tlsCipherSuites | join "," }}
        {{- include "kube-apiserver.apiAudiences" . | indent 8 }}
        {{- include "kube-apiserver.serviceAccountConfig" . | indent 8 }}
        - --v=2
