{{- if .Values.OIDCConfig.caBundle }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-oidc-cabundle
  namespace: {{ .Release.Namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
type: Opaque
data:
  ca.crt: {{ .Values.OIDCConfig.caBundle | b64enc }}
{{- end }}
