{{- if .Values.oidcConfig.caBundle }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-apiserver.oidcCABundle.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    resources.gardener.cloud/garbage-collectable-reference: "true"
immutable: true
data:
{{ include "kube-apiserver.oidcCABundle.data" . | indent 2 }}
{{- end }}
