apiVersion: v1
kind: Service
metadata:
  name: gardener-api-quic-server
  namespace: relay
  labels:
    app:  gardener-api-quic-server
  annotations:
    # For AWS Network Load Balancer needs to be used, because it supports UDP 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
