apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-adapter
  namespace: {{ .Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: custom-metrics-apiserver
