---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scheduler-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  {{ .Values.volumes.config.dataKey }}: |-
    ---
    apiVersion: {{ include "kube-scheduler.componentconfigversion" . }}
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: {{ .Values.volumes.kubeconfig.mountPath }}/kubeconfig
    leaderElection:
      leaderElect: true
