apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:unprivileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
