apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.24.0
  extraPortMappings:
  # istio-ingressgateway
  - containerPort: 30443
    hostPort: 443
    listenAddress: 127.0.0.2
  extraMounts:
  - hostPath: dev/local-backupbuckets
    containerPath: /etc/gardener/local-backupbuckets
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authorization-mode: RBAC,Node
networking:
  disableDefaultCNI: true # disable kindnet since we install calico for network policy support
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.2.0.0/16
