apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  clusterIP: 10.2.0.11
  ports:
  - port: 5001
    targetPort: registry
    nodePort: 30501
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      automountServiceAccountToken: false
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
        - name: registry
          containerPort: 5000
        volumeMounts:
        - name: cache
          mountPath: /var/lib/registry
      volumes:
      - name: cache
        hostPath:
          path: /etc/gardener/local-registry
