# TODO(rfranzke): This NetworkPolicy is deprecated and will be removed in the future.
apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Prometheus to talk to various components in the Seed cluster.
  name: allow-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: prometheus
      gardener.cloud/role: monitoring
      role: monitoring
  egress:
  - to:
    - podSelector:
        matchLabels:
          networking.gardener.cloud/from-prometheus: allowed
  policyTypes:
  - Egress
