apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-api-quic-client
  namespace: relay
  labels:
    app: gardener-api-quic-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gardener-api-quic-client
  template:
    metadata:
      labels:
        app: gardener-api-quic-client
    spec:
      containers:
      - args:
        - --server=$(RELAY_DOMAIN):443
        - --upstream=gardener-apiserver.relay.svc.cluster.local:443
        - --cert-file=/certs/tls.crt
        - --cert-key=/certs/tls.key 
        - --ca-file=/certs/ca.crt
        - --v=2
        image: ghcr.io/mvladev/quic-reverse-http-tunnel/quic-client-tcp:v0.1.3
        name: quic-client
        volumeMounts:
        - name: quic-tls
          mountPath: "/certs"
          readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
      volumes:
      - name: quic-tls
        secret:
          secretName: quic-tls
---
apiVersion: v1
kind: Service
metadata:
  name:  gardener-apiserver
  namespace: relay
  labels:
    app:  gardener-api-quic-server
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
