global:
  admission:
  # kubeconfig: {}
    replicaCount: 3
    serviceAccountName: gardener-admission-controller
    image:
      repository: eu.gcr.io/gardener-project/gardener/admission-controller
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 512Mi
    vpa: false
    config:
      gardenClientConnection:
        acceptContentTypes: application/json
        contentType: application/json
        qps: 100
        burst: 130
      server:
        https:
          bindAddress: 0.0.0.0
          port: 2719
          tls:
            caBundle: |
              -----BEGIN CERTIFICATE-----
              ...
              -----END CERTIFICATE-----
            crt: |
              -----BEGIN CERTIFICATE-----
              ...
              -----END CERTIFICATE-----
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              ...
              -----END RSA PRIVATE KEY-----
    # resourceAdmissionConfiguration:
    #   limits:
    #   - apiGroups: ["core.gardener.cloud"]
    #     apiVersions: ["*"]
    #     resources: ["shoots", "plants"]
    #     size: 100Ki
    #   unrestrictedSubjects:
    #   - kind: Group
    #     name: gardener.cloud:system:seeds
    #     apiGroup: rbac.authorization.k8s.io
    #   operationMode: log
  # Deployment related configuration
  deployment:
    virtualGarden:
      enabled: false
      createNamespace: false
