---
apiVersion: operator.config.gardener.cloud/v1alpha1
kind: OperatorConfiguration
runtimeClientConnection:
  qps: 100
  burst: 130
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
  resourceNamespace: garden
  resourceName: gardener-operator-leader-election
logLevel: info
logFormat: text
server:
  healthProbes:
    bindAddress: 0.0.0.0
    port: 2750
  metrics:
    bindAddress: 0.0.0.0
    port: 2751
debugging:
  enableProfiling: false
  enableContentionProfiling: false
controllers:
  garden:
    concurrentSyncs: 1
    syncPeriod: 1h
