apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-api-quic-server
  namespace: relay
  labels:
    app: gardener-api-quic-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gardener-api-quic-server
  template:
    metadata:
      labels:
        app: gardener-api-quic-server
    spec:
      containers:
      - args:
        - --listen-tcp=0.0.0.0:6443
        - --listen-quic=0.0.0.0:10443
        - --cert-file=/certs/tls.crt
        - --cert-key=/certs/tls.key 
        - --client-ca-file=/certs/ca.crt
        - --v=2
        image: ghcr.io/mvladev/quic-reverse-http-tunnel/quic-server:v0.1.3
        name: quic-server
        volumeMounts:
        - name: quic-tls
          mountPath: "/certs"
          readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
        ports:
        - name: tcp
          containerPort: 6443
        - name: quic
          containerPort: 10443
      volumes:
      - name: quic-tls
        secret:
          secretName: quic-tls
---
apiVersion: v1
kind: Service
metadata:
  name:  gardener-apiserver
  namespace: relay
  labels:
    app:  gardener-api-quic-server
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
    name: https
  selector:
    app:  gardener-api-quic-server
  type: ClusterIP
