name: Delete Garden Resource

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name ora-showroom --debug

    - name: Annotate Garden Resource for Deletion
      run: |
        echo "Annotating the Garden resource for deletion..."
        kubectl annotate garden local confirmation.gardener.cloud/deletion=true --overwrite
        echo "Annotation complete."

    - name: Delete Garden Resource
      run: |
        echo "Deleting the Garden resource..."
        kubectl delete garden/local
        echo "Deletion initiated."