### !CAUTION! ###
# Most cloud providers have a limit of 16 KB regarding the user-data that may be sent during VM creation.
# The result of this operating system config is exactly the user-data that will be sent to the providers.
# We must not exceed the 16 KB, so be careful when extending/changing anything in here.
### !CAUTION! ###
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: OperatingSystemConfig
metadata:
  name: {{ required "osc.name is required" .Values.osc.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/operation: reconcile
    gardener.cloud/timestamp: {{ required "osc.annotationCurrentTimestamp is required" .Values.osc.annotationCurrentTimestamp }}
spec:
  type: {{ required "osc.type is required" .Values.osc.type }}
  purpose: {{ required "osc.purpose is required" .Values.osc.purpose }}
  {{- if .Values.osc.providerConfig }}
  providerConfig:
{{ .Values.osc.providerConfig | indent 4 }}
  {{- end }}
  {{- if .Values.osc.cri }}
  criConfig:
    name: {{ .Values.osc.cri.name }}
  {{- end }}
  units:
{{ include "cloud-config-downloader-service" . | indent 2 }}
  files:
{{ include "cloud-config-downloader-files" . | indent 2 }}
