apiVersion: v1
kind: Namespace
metadata:
  annotations:
{{ include "utils-templates.reconcile-warning-annotation" . | indent 4 }}
  name: kube-system
{{- if .Values.labels }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
