rule_files:
- ../rules/kube-etcd3.rules.yaml

evaluation_interval: 30s

tests:
- interval: 30s
  input_series:
  # KubeEtcdMainDown
  - series: 'up{job="kube-etcd3",role="main"}'
    values: '0+0x20'
  # KubeEtcdEventsDown
  - series: 'up{job="kube-etcd3",role="events"}'
    values: '0+0x30'
  # KubeEtcd3MainNoLeader
  - series: 'etcd_server_has_leader{job="kube-etcd3",role="main"}'
    values: '0+0x20'
  # KubeEtcd3EventsNoLeader
  - series: 'etcd_server_has_leader{job="kube-etcd3",role="events"}'
    values: '0+0x30'
  # KubeEtcd3HighNumberOfFailedProposals
  - series: 'etcd_server_proposals_failed_total{job="kube-etcd3", pod="etcd"}'
    values: '0+2x60 121+0x60'
  # KubeEtcd3DbSizeLimitApproaching
  # KubeEtcd3DbSizeLimitCrossed
  - series: 'etcd_mvcc_db_total_size_in_bytes{job="kube-etcd3",role="main"}'
    values: '7194070000+107374182x20' # 6.7GB 6.8GB 6.9GB .. 7.7GB
  # KubeEtcdDeltaBackupFailed
  - series: 'etcdbr_snapshot_latest_timestamp{job="kube-etcd3-backup-restore",role="main",kind="Incr"}'
    values: '0+0x62'
  - series: 'etcdbr_snapshot_required{job="kube-etcd3-backup-restore",role="main",kind="Incr"}'
    values: '1+0x62'
  # KubeEtcdFullBackupFailed
  - series: 'etcdbr_snapshot_latest_timestamp{job="kube-etcd3-backup-restore",role="main",kind="Full"}'
    values: '0+0x5790'
  - series: 'etcdbr_snapshot_required{job="kube-etcd3-backup-restore",role="main",kind="Full"}'
    values: '1+0x5790'
  # KubeEtcdRestorationFailed
  - series: 'etcdbr_restoration_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",succeeded="false"}'
    values: '0+0x7 1 2 2'
  alert_rule_test:
  - eval_time: 5m
    alertname: KubeEtcdMainDown
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: blocker
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 cluster main is unavailable or cannot be scraped. As long as etcd3 main is down the cluster is unreachable.
        summary: Etcd3 main cluster down.
  - eval_time: 15m
    alertname: KubeEtcdEventsDown
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 cluster events is unavailable or cannot be scraped. Cluster events cannot be collected.
        summary: Etcd3 events cluster down.
  - eval_time: 10m
    alertname: KubeEtcd3MainNoLeader
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 main has no leader. No communication with etcd main possible. Apiserver is read only.
        summary: Etcd3 main has no leader.
  - eval_time: 15m
    alertname: KubeEtcd3EventsNoLeader
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 events has no leader. No communication with etcd events possible. New cluster events cannot be collected. Events can only be read.
        summary: Etcd3 events has no leader.
  - eval_time: 1h
    alertname: KubeEtcd3HighNumberOfFailedProposals
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: warning
        type: seed
        visibility: operator
        pod: etcd
        job: kube-etcd3
      exp_annotations:
        description: Etcd3 pod etcd has seen 121 proposal failures within the last hour.
        summary: High number of failed etcd proposals
  - eval_time: 5m
    alertname: KubeEtcd3DbSizeLimitApproaching
    exp_alerts:
    - exp_labels:
        job: kube-etcd3
        role: main
        service: etcd
        severity: warning
        type: seed
        visibility: all
      exp_annotations:
        description: Etcd3 main DB size is approaching its current practical limit of 8GB. Etcd quota might need to be increased.
        summary: Etcd3 main DB size is approaching its current practical limit.
  - eval_time: 10m
    alertname: KubeEtcd3DbSizeLimitCrossed
    exp_alerts:
    - exp_labels:
        job: kube-etcd3
        role: main
        service: etcd
        severity: critical
        type: seed
        visibility: all
      exp_annotations:
        description: Etcd3 main DB size has crossed its current practical limit of 8GB. Etcd quota must be increased to allow updates.
        summary: Etcd3 main DB size has crossed its current practical limit.
  - eval_time: 31m
    alertname: KubeEtcdDeltaBackupFailed
    exp_alerts:
    - exp_labels:
        job: kube-etcd3-backup-restore
        kind: Incr
        role: main
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: No delta snapshot for the past at least 30 minutes.
        summary: Etcd delta snapshot failure.
  - eval_time: 2896m # 2 days + 16 minutes
    alertname: KubeEtcdFullBackupFailed
    exp_alerts:
    - exp_labels:
        job: kube-etcd3-backup-restore
        kind: Full
        role: main
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: No full snapshot taken in the past 2 days.
        summary: Etcd full snapshot failure.
  - eval_time: 5m
    alertname: KubeEtcdRestorationFailed
    exp_alerts:
    - exp_labels:
        job: kube-etcd3-backup-restore
        succeeded: false
        role: main
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd data restoration was triggered, but has failed.
        summary: Etcd data restoration failure.
